"""io/paths.py — the single path registry for the repo.

Every dataset, artifact, asset and tracking store is resolved through an accessor
here, so relocating storage is a one-line change rather than an edit to hundreds
of call sites (2026-08-03 restructure; see repo_structure.md). Also kills the
CWD-dependent bare filenames that broke cross-module artifact handoff.

REPO_ROOT walks up for a marker instead of counting parents, so moving a module
deeper in the tree cannot break it.
"""
from __future__ import annotations

import os
from pathlib import Path

_MARKERS = ("pyproject.toml", ".git")


def _find_root(start: Path) -> Path:
    for cand in (start, *start.parents):
        if any((cand / m).exists() for m in _MARKERS):
            return cand
    raise RuntimeError(f"no repo root marker {_MARKERS} above {start}")


REPO_ROOT = _find_root(Path(__file__).resolve())


def _ensure(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p


# --- generated data (DVC-tracked); LCP_DATA overrides the whole tree ---

def data_dir() -> Path:
    return _ensure(Path(os.environ.get("LCP_DATA", REPO_ROOT / "data")))


def derived_dir() -> Path:
    return _ensure(data_dir() / "derived")


def sep_dir() -> Path:
    """Checkpoint bay for the separated/certified field family."""
    return _ensure(derived_dir() / "sep")


def reach_dir() -> Path:
    return _ensure(derived_dir() / "reach")


def shards_dir() -> Path:
    return _ensure(data_dir() / "shards")


def records_dir() -> Path:
    return _ensure(data_dir() / "records")


def selfplay_dir() -> Path:
    return _ensure(data_dir() / "selfplay")


def lichess_dir() -> Path:
    return _ensure(data_dir() / "lichess")


# --- artifacts ---

def artifacts_dir() -> Path:
    return _ensure(REPO_ROOT / "artifacts")


def generated_dir() -> Path:
    """Regenerable viz output -- gitignored."""
    return _ensure(artifacts_dir() / "generated")


def experiments_dir() -> Path:
    """Structured experiment_report.py JSON records -- small and valuable
    (a research history, like JOURNAL.md), NOT gitignored unlike generated_dir()."""
    return _ensure(artifacts_dir() / "experiments")


def docs_dir() -> Path:
    return _ensure(REPO_ROOT / "docs")


def figures_dir() -> Path:
    return _ensure(docs_dir() / "figures")


# --- third-party assets: downloaded, never generated by us ---

def assets_dir() -> Path:
    return _ensure(REPO_ROOT / "assets")


def syzygy_dir() -> Path:
    """Syzygy tablebases; SYZYGY_PATH overrides (python-chess convention)."""
    env = os.environ.get("SYZYGY_PATH")
    return Path(env) if env else _ensure(assets_dir() / "tablebases" / "syzygy")


def engines_dir() -> Path:
    """Third-party engine binaries/weights (lc0, maia)."""
    return _ensure(assets_dir() / "engines")


def maia2_models_dir() -> Path:
    """maia2.from_pretrained() download target -- 267MB, gitignored."""
    return _ensure(assets_dir() / "models" / "maia2")


def corpora_dir() -> Path:
    """Raw third-party corpora (lichess PGN dumps, puzzle db, ECO tables)."""
    return _ensure(assets_dir() / "corpora")


def raw_dir() -> Path:
    return _ensure(corpora_dir() / "raw")


def eco_dir() -> Path:
    return _ensure(corpora_dir() / "eco")


def puzzle_db() -> Path:
    return corpora_dir() / "lichess_db_puzzle.csv.zst"


# --- experiment tracking: one store, wherever we are invoked from ---

def mlflow_db() -> Path:
    return REPO_ROOT / "mlflow.db"


def mlflow_uri() -> str:
    """Honour MLFLOW_TRACKING_URI, else the repo-root sqlite store."""
    return os.environ.get("MLFLOW_TRACKING_URI") or f"sqlite:///{mlflow_db()}"


def mlruns_dir() -> Path:
    return _ensure(REPO_ROOT / "mlruns")


# --- helpers ---

def newest_shard_dir() -> Path:
    """Most recently modified shard directory -- the default training/eval dataset."""
    dirs = [p for p in shards_dir().iterdir() if p.is_dir() and list(p.glob("shard_*.npz"))]
    if not dirs:
        raise SystemExit(
            "no shard dirs under shards_dir() -- run experiments/build_lichess_shards.py first")
    return max(dirs, key=lambda p: p.stat().st_mtime)


def save_array(name: str, arr, sub: str = "derived") -> Path:
    import numpy as np
    base = derived_dir() if sub == "derived" else data_dir() / sub
    base.mkdir(parents=True, exist_ok=True)
    path = base / f"{name}.npy"
    np.save(path, arr)
    return path


def load_array(name: str, sub: str = "derived"):
    import numpy as np
    base = derived_dir() if sub == "derived" else data_dir() / sub
    return np.load(base / f"{name}.npy")
